### ISSUE TITLE
Добавить границы для расчетной ячейки

### ISSUE THREAD

**Issue by Ladsers** [unn44/MM-IdealGas#2]
Иными словами, нарисовать квадрат по границам массива (или что там у тебя используется).

**Comment by Ladsers** [comment]
Можно просто цветом выделить "расчетный" квадрат, если так удобней. Но без какого-либо обозначения расчетной ячейки грустно :(

**Comment by milkweed123** [comment]
Там через border сделать тяжело, наверное как нибудь через  бэкграунд сделаю

**Comment by Ladsers** [comment]
> Там через border сделать тяжело, наверное как нибудь через бэкграунд сделаю

Если ты имеешь в виду тэги в xaml, то там, что border, что background, просто всё поле канваса целиком обводят (я пробовал), а нам это не надо.. надо именно квадрат нарисовать.. а уж залить или обвести 1px вокруг, тут на самом деле невелика разница

**Comment by milkweed123** [comment]
Ну это можно просто контролить width и height у самих эллипсов ну это не главная проблема пока что

**Comment by Ladsers** [comment]
Не оч понял как связаны размеры эллипсов и граница)

**Comment by Ladsers** [comment]
> через лево и верх нормально переходит, а через право и низ нет

**Comment by milkweed123** [comment]
Там проект падает из -за того что сила руинит всё, там пишет что индекса нет , который кот хочет

**Comment by Ladsers** [comment]
Переход не по половине частицы, а целиком.
