### ISSUE TITLE
Проблема с биндингами

### ISSUE THREAD

**Issue by ladsy44** [unn44/MM-IdealGas#6]
Некорректно работает изменение шага по времени через окно приложения, т.е. шаг по времени в любом случае равен начальной инициализации. Возможно на каких-то полях ввода имеется аналогичная проблема.

**Comment by milkweed123** [comment]
Реализовано.

**Comment by milkweed123** [comment]
Там проект падает из -за того что сила руинит всё, там пишет что индекса  нет ,  который кот хочет
