### ISSUE TITLE
Перевод реальных координат в пиксели после вычислений

### ISSUE THREAD

**Issue by ladsy44** [unn44/MM-IdealGas#7]
Васин предложил отказаться от "пикселей" в расчетах, а использовать реальные цифры и размерность. Посчитать n-ое количество шагов по времени (те же 500 шагов), перевести их (т.е. всё итоговое поле 30ах30а со всеми координатами частиц) в пиксели с некоторым шагом и по таймеру построить.

Сейчас мы сначала переводим всё в пиксели, а потом считаем.

+ Малая вероятность ошибиться в расчётах.
+ Удобный доступ к реальным данным, что может пригодиться при построении различных распределений.

- Придется переписать некоторые участки кода (например, избавиться от шага в переменных _world...)
- Придется реализовать класс, который преобразует поле в 2D картинку.

**Comment by ladsy44** [comment]
@milkweed123 я сначала же, если помнишь, хотел через 2d массив всё делать, поэтому там важно было наличие массива, а сейчас никакого массива нету, есть только список с положениями центров, так что это реализуемо. Так что я могу переписать.

**Comment by ladsy44** [comment]
>     * Придется реализовать класс, который преобразует поле в 2D картинку.

@milkweed123 Или не придется? Канвас случайно не умеет работать с дробными числами? Тока с пикселями?

**Comment by milkweed123** [comment]
Канвас прекрасно работает с double положением эллипсов, зачем делать 2D картинку историю умалчивает
