### ISSUE TITLE
Количество сделанных шагов

### ISSUE THREAD

**Issue by Ladsers** [unn44/MM-IdealGas#9]
Предлагаю добавить счетчик сделанных шагов, чтобы не быть голословными.

Хотя вот так, по ощущениям, очень много проходит шагов перед тем, как все частицы улетают.

**Comment by Ladsers** [comment]
@milkweed123 ну я добавлю короче?

**Comment by milkweed123** [comment]
Можно, но не обяазательно, хм, сейчас я кое чё сделаю, мне кажется я понял в чём причина того что они улетают

**Comment by Ladsers** [comment]
@milkweed123 ну типа Васин такой: "так а сколько у вас шагов то сделано.. я типа не вижу.. мб у вас 100 шагов, а может 100к сделано", а мы ему ничего внятного не ответим.

Давай!

**Comment by Ladsers** [comment]
Кстати, я сейчас пару раз запускал.. ну они очень долго разлетаются, конечно...

**Comment by milkweed123** [comment]
Ща всё пофикшу, не сцы)

**Comment by Ladsers** [comment]
Заинтригован
